### ISSUE TITLE
Release 19.05?

### ISSUE THREAD

**Issue by brianjmurrell** [spdk/dpdk#2]
SPDK v19.04.1 makes reference to:

DPDK
Added DPDK 19.05 support.

But I don't see any 19.05 release here.  Latest seems to be v18.08.  Is dpdk behind on making some releases?

**Comment by jimharris** [comment]
Hi Brian,

DPDK makes quarterly releases.  Their last release was v19.08 (August 2019).  But the place to look for DPDK releases isn't the spdk/dpdk project - that is SPDK's submodule that points to some release of DPDK plus a small number of patches to optimize or fix usage of that version of DPDK with SPDK.  https://git.dpdk.org/dpdk/ points to the full set of available DPDK releases.

For v19.04.1, our DPDK submodule points to DPDK v19.02 plus 10 SPDK-specific patches.  (Do a 'git log --oneline" from the dpdk directory after checking out the spdk v19.04.1 branch).  The comment "Added DPDK 19.05 support" means that users can now build SPDK against a separate DPDK v19.05 tree, using the --with-dpdk=<dpdk path> configure option.  This is frequently how we handle versions of DPDK that come out right after an SPDK release.

SPDK commit a994009f30 shows the kind of changes that get merged to support building SPDK with the newer DPDK release.

Hope this makes sense.  Let us know if you have any further questions.

-Jim

**Comment by brianjmurrell** [comment]
@jimharris Yeah, thanks.  I'm starting to make sense of this now that I have investigated a bit more.

Tangentially, if I were trying to create a stand-alone dpdk suitable for spdk, any idea what options (i.e. what the `make` commandline looks like) spdk uses when it `makes` dpdk?

**Comment by brianjmurrell** [comment]
@jimharris Related to this, would it be possible to update (and keep it updated) your mirror of dpdk so that it has all of the tags from http://git.dpdk.org/dpdk/?  It might make it less confusing about where the fork here is in relation to the upstream DPDK source.

For example, it wouldn't make:
```bash
$ git submodule status
 fdb511332624e28631f553a226abb1dc0b35b28a dpdk (v18.08-5983-gfdb5113)
```

so _frightening_ looking.  :smile:

**Comment by jimharris** [comment]
Good catch @brianjmurrell.  @Seth5141 we should add this to our process when we update the DPDK submodule.  Could you push the latest upstream DPDK tags to our DPDK fork?  And then we can just update the tags again each time we update our submodule.

**Comment by brianjmurrell** [comment]
@jimharris So glad to hear that you agree and are going to rectify this.

Should make things more clear for people new to the project and trying to understand the relationship of dpdk to spdk.

**Comment by Seth5141** [comment]
@brianjmurrell Thanks for pointing that out. I have updated the tags on our DPDK submodule. Please verify on your local repo and if you are satisfied, please close this issue.

**Comment by brianjmurrell** [comment]
Oh yes, this looks much more sane:

```
$ git submodule status
 67b915b09bcf51ae2e2a703718881f0b0845883c dpdk (v19.02-10-g67b915b09)
```

Thanks much!

**Comment by brianjmurrell** [comment]
Did this regress or are tags from the dpdk upstream no longer getting published?

```
$ git submodule status
 56963a26a45cba28e9a613b4a8cfee75f792564e dpdk (v20.11-944-g56963a26a4)
```

But if I look at the dpdk submodule commit history:

```
* 56963a26a4 - (HEAD, origin/spdk-21.02) pci/linux: free the device if no kernel driver configured (3 months ago) <Tomasz Zawadzki>
* daf36df32d - build/meson: disable qat_asym driver (3 months ago) <Darek Stojaczyk>
* 60233d20e3 - build/meson: disable libraries we don't need (3 months ago) <Darek Stojaczyk>
* 543f40f595 - version: 21.02.0 (4 months ago) <Thomas Monjalon>
```

It looks like it's just a few commits on top of 21.02[-rc4].  So did that tag not actually happen in the dpdk upstream or did it fail to get synced in your fork?

**Comment by jimharris** [comment]
This is a regression.  I'm looking at it now.

**Comment by jimharris** [comment]
Can you take another look?  I've just pushed some of the DPDK tags to our fork.

We need to circle back and make sure this is getting done regularly when we update submodules.
