### ISSUE TITLE
Mention move to own git hosting 

### ISSUE THREAD

**Issue by zeenix** [spdk/dpdk#5]
I thought this was the canonical repository until i noticed the 3-year old timestamp on the latest commit. It would save time for a lot of people if the move to the [own git repo hosting](https://www.dpdk.org/contribute/) was documented in the README here. I can provide a PR for that if you like?

**Comment by jimharris** [comment]
This is the canonical repository for SPDK's dpdk submodule.  The dpdk submodule never points to master - it always points to a spdk-xx.yy branch.  These branches start with the DPDK xx.yy release, and add a few extra commits, typically disabling libraries and PMD drivers that SPDK does not require.  You will see much more recent commits on these branches.

For anyone who wants latest DPDK master, it's suggested to point to the DPDK repository directly.

**Comment by zeenix** [comment]
Thanks for the very quick response and explanation. 

> This is the canonical repository for SPDK's dpdk submodule. The dpdk submodule never points to master - it always points to a spdk-xx.yy branch. These branches start with the DPDK xx.yy release, and add a few extra commits, typically disabling libraries and PMD drivers that SPDK does not require. You will see much more recent commits on these branches.

Ah ok. Perhaps this should be mentioned in the README on the master branch then and master shouldn't have any files other than README so people don't get confused?

There is also the option of specifying in the github settings which branch is the main one.

**Comment by jimharris** [comment]
> Ah ok. Perhaps this should be mentioned in the README on the master branch then and master shouldn't have any files other than README so people don't get confused?
> 
> There is also the option of specifying in the github settings which branch is the main one.

I've changed the default branch to spdk-21.05.  @tomzawadzki, we will want to remember to update this when we move the DPDK submodule to spdk-21.08 (and others) in the future.

**Comment by jimharris** [comment]
Thanks @zeenix!
